language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
install:
    - pip install nose coverage --use-mirrors
    - pip install . --use-mirrors
    # cd outside srcdir, it confuses Python 3.2
    - cd doc
script: nosetests --with-coverage --with-doctest --cover-package=monologue monologue
